from enum import IntEnum

class command(IntEnum):
    SET_NEW_WRITER_DURATION = 245
    SET_NEW_READER_DURATION = 246
    GET_WRITER_DURATION = 247
    GET_READER_DURATION = 248
    GET_FILE_CONTENT = 249
    GET_WRITE_RESULT = 250
    MODIFY_FILE = 251
    REMOVE_FILE = 252
    ADD_FILE = 253
    HAS_FILE = 254
    SEARCH = 255
    
class response(IntEnum):
    OK = 0
    INVALID_COMMAND = 1
    ERROR_RECEIVING_COMMAND = 2
    ERROR_RECEIVING_DATA = 3
    ARGUMENT_IS_ZERO = 4
    SEARCH_QUERY_ENTRIES_NOT_FOUND = 5
    FILE_NOT_FOUND = 6
    COULD_NOT_ADD_FILE = 7
    NEW_DURATION_IS_WAY_TOO_SMALL = 8
    OPERATION_IS_NOT_PROCESSED = 9
    OPERATION_IS_IN_PROGRESS = 10
    WRITE_TASK_ID_NOT_FOUND = 11